// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrluhxwootpggtptglcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybHVoeHdvb3RwZ2d0cHRnbGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTc2MTMsImV4cCI6MjA2ODY5MzYxM30.aH9JWZ3hLtC-hOo3iBbJK64edLFkyJYkHXdOavANXMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});